spring:
  #开发环境申明
  config:
    activate:
      on-profile: dev
  #配置文件编码
  mvc:
    cotent-negotiation-manager:
      #默认编码
      default-charset: UTF-8
#静态文件上传配置
  servlet:
    multipart:
      location: /var/www/uploads/  # 临时文件存储位置
      max-file-size: 200MB  # 单个文件的最大大小
      max-request-size: 250MB  # 单次请求的最大总大小

#redis的主机ip及端口
  data:
    redis:
      host: 127.0.0.1
      # 端口
      port: 6379
      # 数据库索引
      database: 0
      # 密码
      password: 123456
      # 连接超时时间
      timeout: 10s
      #lettuce连接池配置
      lettuce:
        pool:
          #最大连接数
          max-active: 32
          #最大阻塞等待时间数（负数表示没有限制）
          max-wait: -1
          #最大空闲
          max-idle: 16
          #最小空闲
          min-idle: 0
        #连接超时时间
        timeout: 2000a
    mongodb:
      uri: mongodb://admin:123456@localhost:27017/showcase
      # 是否自动创建索引
      auto-index-creation: true
      connection-string:
        #最大连接数
        max-connections-per-host: 100
        #最大等待时间
        max-wait-time-ms: 5000
        #心跳频率
        heartbeat-frequency-ms: 10000
        #心跳连接超时时间
        heartbeat-connect-timeout-ms: 20000
        #连接超时时间
        connect-timeout-ms: 10000
        #socket超时时间
        socket-timeout-ms: 0
        #socket保持连接
        socket-keep-alive: true
        #服务器选择超时时间
        server-selection-timeout-ms: 10000

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

#mysql数据库连接配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      url: jdbc:postgresql://127.0.0.1:5432/psm?serverTimezone=UTC
      username: admin
      password: 123456
      driver-class-name: org.postgresql.Driver

#服务器地址及端口
server:
  port: 8000
  address: 127.0.0.1

#mybaitis-plus配置
mybatis-plus:
  global-config:
    db-config:
#      table-prefix: tb_ #数据表前缀

      logic-delete-field: deleted #全局逻辑删除的实体字段名
      logic-delete-value: true #逻辑已删除值(默认为 1)
      logic-not-delete-value: false #逻辑未删除值(默认为 0)
  configuration:
    map-underscore-to-camel-case: true #开启驼峰命名
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #日志配置
  #实体类所对应的包
  type-aliases-package: com.psm.domain
  #扫描通用枚举的包
  type-enums-package: com.psm.enums

#阿里云配置信息
aliyun:
  #oss服务
  oss:
    endpoint: https://oss-cn-guangzhou.aliyuncs.com
    access-key-id: LTAI5t8QXMXdHCpCorzzkVi2
    access-key-secret: Bv31pl1AcYEryStLmeN1cJksmshROK
    bucket-name: new-psm

    #oss文件路径配置
    path:
      subtitles:
        imageFolderPath: subtitles/covers
        videoFolderPath: subtitles/videos

#jwt配置
jwt:
  #jwt签发者
  issuer: moye
  #jwt加密密钥
  secret: moyesprite
  #jwt过期时间
  expiration: 3600000 #1小时
  #jwt刷新时间
  refresh-expiration: 900000 #15分钟