#开发环境申明
spring:
  profiles: dev

#redis的主机ip及端口
  redis:
    host: 127.0.0.1
    # 端口
    port: 6379
    # 数据库索引
    database: 0
    # 密码
    password: 123456
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        #最大连接数
        max-active: 32
        #最大阻塞等待时间数（负数表示没有限制）
        max-wait: -1
        #最大空闲
        max-idle: 16
        #最小空闲
        min-idle: 0
      #连接超时时间
      timeout: 2000

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

#mysql数据库连接配置
  datasource:
    druid:
      url: jdbc:mysql:///psm?serverTimezone=UTC
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver

#服务器地址及端口
server:
  port: 8000
  address: 127.0.0.1

#mybaitis-plus配置
mybatis-plus:
  global-config:
    db-config:
#      table-prefix: tb_ #数据表前缀

      logic-delete-field: deleted #全局逻辑删除的实体字段名
      logic-delete-value: 1 #逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 #逻辑未删除值(默认为 0)
  configuration:
    map-underscore-to-camel-case: true #开启驼峰命名
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #日志配置
  #实体类所对应的包
  type-aliases-package: com.psm.domain
  #扫描通用枚举的包
  type-enums-package: com.psm.enums